---
name: Build - Flatpak
permissions:
  contents: read

on:
  workflow_call:
    inputs:
      ci_version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FLATPAK_ID: com.foggybytes.StreamLight
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          submodules: 'recursive'
          fetch-depth: 1

      - name: Build Flatpak
        uses: flathub-infra/flatpak-github-actions@v1
        with:
          bundle: ${{ env.FLATPAK_ID }}
          manifest-path: com.foggybytes.StreamLight.json
          cache-build-dir: false

      - name: Rename and Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: StreamLight-Flatpak-${{ inputs.ci_version }}
          path: ${{ env.FLATPAK_ID }}.flatpak
          compression-level: 0
          if-no-files-found: error

      - name: Rename for Release
        run: |
          mv ${{ env.FLATPAK_ID }}.flatpak ${{ env.FLATPAK_ID }}-${{ inputs.ci_version }}.flatpak
